const sections = [
  `Welcome to Vulcan!`,
  `Creating a Route`,
  `Registering a Component`,
  `React Hooks`,
  `Core Components`,
  `Schemas`,
  `Collections`,
  `The GraphQL Schema`,
  `Seeding Data`,
  `Resolvers`,
  `Loading Data`,
  `Fragments`,
  `Relations`,
  `User Accounts`,
  `Mutations`,
  `Forms`,
  `Datatables`,
  `Permissions`,
  `Sorting & Filtering`,
  `Internationalization`,
  `Next Steps`,
];

export default sections;
