const sections = [
  `Welcome to Vulcan!`,
  `Creating a Route`,
  `Registering a Component`,
  `Importing Components`,
  `Core Components`,
  `Schemas`,
  `Collections`,
  `The GraphQL Schema`,
  `Seeding Data`,
  `Resolvers`,
  `Loading Data`,
  `Fragments`,
  `Field Resolvers`,
  `User Accounts`,
  `Mutations`,
  `Forms`,
  `Datatables`,
  `Permissions`,
  `Sorting`,
  `Internationalization`,
  `Next Steps`,
];

export default sections;